services:
  db:
    image: postgres:13
    container_name: my_db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - sleepdb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    image: myapp_image
    container_name: my_app
    depends_on:
      - db
    ports:
      - "8080:8080"

# Определение тома sleepdb_data
volumes:
  sleepdb_data:
