services:
  app:
    image: postgres
    container_name: my_app
    environment:
      - DB_HOST=localhost      # Здесь указываем хост базы данных
      - DB_PORT=5432          # Порт базы данных
      - DB_USER=postgres     # Имя пользователя базы данных
      - DB_PASSWORD=123  # Пароль пользователя базы данных
      - DB_NAME=sleepdb  # Имя базы данных
    ports:
      - "8080:8080"
    
