version: '3.4'

services:
  web:
    image: sleeptrackerapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Username=postgres;Password=123;Database=sleepdb
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sleepdb
    volumes:
      - sleepdb_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sleeptracker_data:
